# Generated by Django 4.0.6 on 2022-07-24 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
